version: '3.8'

services:
  agents-system:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./logs:/app/logs
      - ./data:/app/data
    environment:
      - DOUBAO_API_KEY=${DOUBAO_API_KEY}
      - FEISHU_APP_ID=${FEISHU_APP_ID}
      - FEISHU_APP_SECRET=${FEISHU_APP_SECRET}
      - FEISHU_VERIFY_TOKEN=${FEISHU_VERIFY_TOKEN}
      - FEISHU_ENCRYPT_KEY=${FEISHU_ENCRYPT_KEY}
    env_file:
      - .env